control/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope "/admin" do
    resources :users, except: [:new, :create] do
      patch :approve, :on => :member
      patch :update_profile, :on => :member
    end
    resources :workers do
      post :request_config, :on => :member
    end
    resources :repositories do
      post :fetch_branches, :on => :member
      post :post_hook, :on => :member
    end
    resources :enviroments
    resources :base_versions
    resources :issue_trackers
    resources :home_page_contents, except: [:show]
    resources :tests_executors
  end
  get 'users/profile', as: 'user_root'
  
  resources :admin, only: [:index]
  resources :build_numbers, only: [:index, :show] do
    post :generate, :on => :collection
  end
  
  resources :enviroments, param: :title, path: "/", only: [] do
    resources :build_jobs, only: [:index, :show, :new, :create, :destroy] do
      delete :stop, :on => :member
      get :check_existing, :on => :collection
      resources :tests_results, only: [:index, :show]
    end
    resources :build_logs, only: [:show]
    resources :build_artefacts, only: [:show], :param => :filename, :filename => /.*/, :format => false
    resources :live_updates, only: [] do
      get :build_jobs, :on => :collection
    end
  end
  resources :dynamic_stylesheets, only: [:index]
  
  get '/:enviroment_title', to: 'build_jobs#enviroments', as: 'home_enviroments'

  root 'home#index'

end

control/app/views/admin/index.html.haml
- title "Admin area"
  
%h1.page-header= yield(:title)

.row
  .col-md-6
    .list-group
      .list-group-item
        %span.glyphicon.glyphicon-user
          %span= link_to "Users accounts", users_path
      .list-group-item
        %span.glyphicon.glyphicon-cog
          %span= link_to "Workers", workers_path
      .list-group-item
        %span.glyphicon.glyphicon-hdd
          %span= link_to "Repositories", repositories_path
      .list-group-item
        %span.glyphicon.glyphicon-road
          %span= link_to "Enviroments", enviroments_path
      .list-group-item
        %span.glyphicon.glyphicon-random
          %span= link_to "Build numbers", build_numbers_path
      .list-group-item
        %span.glyphicon.glyphicon-bullhorn
          %span= link_to "Base versions", base_versions_path
      .list-group-item
        %span.glyphicon.glyphicon-list-alt
          %span= link_to "Issue trackers", issue_trackers_path
      .list-group-item
        %span.glyphicon.glyphicon-fire
          %span= link_to "Tests executors", tests_executors_path 
      .list-group-item
        %span.glyphicon.glyphicon-home
          %span= link_to "Home page contents", home_page_contents_path