control/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope "/admin" do
    resources :users, except: [:new, :create] do
      patch :approve, :on => :member
      patch :update_profile, :on => :member
    end
    resources :workers do
      post :request_config, :on => :member
    end
    resources :repositories do
      post :fetch_branches, :on => :member
      post :post_hook, :on => :member
    end
    resources :enviroments
    resources :base_versions
    resources :issue_trackers
    resources :home_page_contents, except: [:show]
    resources :tests_executors
  end
  get 'users/profile', as: 'user_root'
  
  resources :admin, only: [:index]
  resources :build_numbers, only: [:index, :show] do
    post :generate, :on => :collection
  end
  
  resources :enviroments, param: :title, path: "/", only: [] do
    resources :build_jobs, only: [:index, :show, :new, :create, :destroy] do
      delete :stop, :on => :member
      get :check_existing, :on => :collection
      resources :tests_results, only: [:index, :show]
    end
    resources :build_logs, only: [:show]
    resources :build_artefacts, only: [:show], :param => :filename, :filename => /.*/, :format => false
    resources :live_updates, only: [] do
      get :build_jobs, :on => :collection
    end
  end
  resources :dynamic_stylesheets, only: [:index]
  
  get '/:enviroment_title', to: 'build_jobs#enviroments', as: 'home_enviroments'

  root 'home#index'

end

control/app/models/tests_executor.rb
class TestsExecutor < ActiveRecord::Base
  has_many :enviroments
  has_many :tests_results
  
  validates :title, length: {in: 1..100}, uniqueness: true
  validates :run_params, length: {in: 1..512}
  validates :artefact_name, length: {in: 1..512}, :format => {:with => /(\.|\/)(zip)/i, :message => "should ends with zip"}
end

control/app/controllers/tests_executors_controller.rb
class TestsExecutorsController < BaseAdminController
  before_action :set_tests_executor, only: [:show, :edit, :update, :destroy]

  # GET /tests_executors
  # GET /tests_executors.json
  def index
    @tests_executors = TestsExecutor.all
  end

  # GET /tests_executors/1
  # GET /tests_executors/1.json
  def show
  end

  # GET /tests_executors/new
  def new
    @tests_executor = TestsExecutor.new
  end

  # GET /tests_executors/1/edit
  def edit
  end

  # POST /tests_executors
  # POST /tests_executors.json
  def create
    @tests_executor = TestsExecutor.new(tests_executor_params)

    respond_to do |format|
      if @tests_executor.save
        format.html { redirect_to @tests_executor, notice: 'Tests executor was successfully created.' }
        format.json { render :show, status: :created, location: @tests_executor }
      else
        format.html { render :new }
        format.json { render json: @tests_executor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests_executors/1
  # PATCH/PUT /tests_executors/1.json
  def update
    respond_to do |format|
      if @tests_executor.update(tests_executor_params)
        format.html { redirect_to @tests_executor, notice: 'Tests executor was successfully updated.' }
        format.json { render :show, status: :ok, location: @tests_executor }
      else
        format.html { render :edit }
        format.json { render json: @tests_executor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests_executors/1
  # DELETE /tests_executors/1.json
  def destroy
    @tests_executor.destroy
    respond_to do |format|
      format.html { redirect_to tests_executors_url, notice: 'Tests executor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tests_executor
      @tests_executor = TestsExecutor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tests_executor_params
      params.require(:tests_executor).permit(:title, :run_params, :artefact_name)
    end
end

control/app/helpers/tests_executors_helper.rb
module TestsExecutorsHelper
end

control/app/views/tests_executors/_form.html.haml
= bootstrap_form_for(@tests_executor, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f|
  = f.text_field :title
  = f.text_field :run_params
  = f.text_field :artefact_name
  = f.primary 'Save'
  - if not defined?(delete_disabled) or not delete_disabled
    = link_to 'Delete this tests executor', @tests_executor, :method => :delete, :class => "btn btn-danger pull-right", :data => { :confirm => 'Are you sure?' }

control/app/views/tests_executors/edit.html.haml
- title "Editing tests executor #{@tests_executor.title}"

%h1.page-header= yield(:title)

.row
  .col-md-12
    = render partial: 'form'

control/app/views/tests_executors/index.html.haml
- title "List tests executors"
  
%h1.page-header= yield(:title)

.row
  .col-md-12
    %table.table.table-striped.table-bordered.table-hover.table-responsive
      %tr
        %th Title
        %th Run params
        %th Artefact name
        %th More info
        
      - @tests_executors.each do |t|
        %tr
          %td= t.title
          %td= t.run_params
          %td= t.artefact_name
          %td= link_to content_tag(:span, "", :class => "glyphicon glyphicon glyphicon-list"), t, :class => "btn btn-default"
  
    = link_to 'Add new tests executor', new_tests_executor_path, class: "btn btn-primary"

control/app/views/tests_executors/new.html.haml
- title "Add new tests executor"

%h1.page-header= yield(:title)

.row
  .col-md-12
    = render partial: 'form', locals: {delete_disabled: true}

control/app/views/tests_executors/show.html.haml
- title "Tests executor info"

%h1.page-header= yield(:title)

.row
  .col-md-12
    %dl.dl-horizontal
      %dt Title
      %dd= @tests_executor.title
      %dt Run params
      %dd= @tests_executor.run_params
      %dt Result artefact name
      %dd= @tests_executor.artefact_name

.row
  .col-md-12
    = link_to 'Edit tests executor', edit_tests_executor_path(@tests_executor), class: "btn btn-primary"