control/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope "/admin" do
    resources :users, except: [:new, :create] do
      patch :approve, :on => :member
      patch :update_profile, :on => :member
    end
    resources :workers do
      post :request_config, :on => :member
    end
    resources :repositories do
      post :fetch_branches, :on => :member
      post :post_hook, :on => :member
    end
    resources :enviroments
    resources :base_versions
    resources :issue_trackers
    resources :home_page_contents, except: [:show]
    resources :tests_executors
  end
  get 'users/profile', as: 'user_root'
  
  resources :admin, only: [:index]
  resources :build_numbers, only: [:index, :show] do
    post :generate, :on => :collection
  end
  
  resources :enviroments, param: :title, path: "/", only: [] do
    resources :build_jobs, only: [:index, :show, :new, :create, :destroy] do
      delete :stop, :on => :member
      get :check_existing, :on => :collection
      resources :tests_results, only: [:index, :show]
    end
    resources :build_logs, only: [:show]
    resources :build_artefacts, only: [:show], :param => :filename, :filename => /.*/, :format => false
    resources :live_updates, only: [] do
      get :build_jobs, :on => :collection
    end
  end
  resources :dynamic_stylesheets, only: [:index]
  
  get '/:enviroment_title', to: 'build_jobs#enviroments', as: 'home_enviroments'

  root 'home#index'

end

control/app/models/repository.rb
class Repository < ActiveRecord::Base
  enum vcs_type: [:git]
  has_many :branches
  has_many :enviroments
  
  validates :title, length: {in: 1..100}, uniqueness: true
  validates :path, length: {in: 1..4000}
  validates :vcs_type, inclusion: {in: Repository.vcs_types.keys}
  validates :weblink_to_commit, format: { with: /:commit/, message: "must contain ':commit' for substitution" }, allow_blank: true
  validate :path_correctness
  
  def branches(force_fetch=false)
    begin
      vcs = vcs_by_type vcs_type
      
      if force_fetch
        fetch_branches_with_last_commit vcs
      end
      
    rescue => e
      self.errors.add(:branches, e.to_s)
    end
    Branch.all_active
  end
  
  def remote_url
    vcs = vcs_by_type vcs_type
    vcs.remote_url
  end
  
  def remote_name
    vcs = vcs_by_type vcs_type
    vcs.remote_name
  end
  
  def full_weblink_to_commit(commit)
    unless self.weblink_to_commit.nil?
      self.weblink_to_commit.sub(":commit", commit)
    else
      nil
    end
  end
  
  def self.fetch_branches_all_in_backgroud
    Rails.logger.debug "Fetching remote branches initialized for each repository"
    Repository.all.each do |r|
      FetchBranchesJob.perform_later r
    end
  end
  
  protected
  
    def vcs_by_type(type)
      case type
      when 'git'
        vcs = Vcs::Git.new(path)
      else
        vcs = Vcs::Base.new(path)
      end
      vcs
    end
    
    def fetch_branches_with_last_commit(vcs)
      Rails.logger.info "Fetching remote branches"
      branches_with_commits = vcs.branches_with_last_commit
      branches_with_commits_names = branches_with_commits.map{|f,s| f}
      unless branches_with_commits.nil?
        Branch.remove_deleted self, branches_with_commits_names # remove deleted in repo branches
        branches_to_create = branches_with_commits - Branch.all_active.map {|b| [b.name, b.last_commit_identifier] } # make a list of only new branches
        branches_to_create.each do |name, commit|
          found = Branch.find_by(:name => name)
          if found
            found.last_commit_identifier = commit
            found.save
          else
            Branch.create(name: name, last_commit_identifier: commit, repository: self)
          end
        end
        Branch.restore_deleted self, branches_with_commits_names
      end
    end
    
    def path_correctness
      vcs = vcs_by_type vcs_type
      vcs.check_correctness
    rescue => err
      errors.add(:path, err.to_s)
    end
  
end

control/app/controllers/repositories_controller.rb
class RepositoriesController < BaseAdminController
  before_filter :set_repository, only: [:show, :edit, :update, :destroy, :fetch_branches, :post_hook]
  skip_before_filter :check_user_admin, only: [:fetch_branches]
  skip_before_filter :authenticate_user!, only: [:post_hook]
  skip_before_filter :check_user_admin, only: [:post_hook]
  skip_before_filter :verify_authenticity_token, only: [:post_hook]
  before_filter :authenticate_hook, only: [:post_hook]
  
  # GET /repositories
  def index
    @repositories = Repository.all
  end

  # GET /repositories/1
  def show
  end

  # GET /repositories/new
  def new
    @repository = Repository.new
  end

  # GET /repositories/1/edit
  def edit
  end

  # POST /repositories
  def create
    @repository = Repository.new(repository_params)
    if @repository.save
      redirect_to @repository, notice: 'Repository was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /repositories/1
  def update
    if @repository.update_attributes(repository_params)
      redirect_to @repository, notice: 'Repository was successfully updated.'
    else
      render action: "edit"
    end
  end
  
  # DELETE /repositories/1
  def destroy
    @repository.destroy
    redirect_to repositories_path, notice: "Repository #{@repository.title} was successfully deleted."
  end
  
  # POST /repositories/1/fetch_branches
  def fetch_branches
    @repository.branches true
    if @repository.errors.empty?
      redirect_to :back, notice: 'Branches were successfully updated.'
    else
      redirect_to :back, flash: {error: "Error fetching remote branches: #{@repository.errors.messages[:branches].join(", ")}."}
    end
  end
  
  # POST /repositories/1/post_hook
  def post_hook
    Rails.logger.info "Repository POST hook triggerd"
    if @repository.hook_enabled
      # here we only updating branches list, in future it's a good idea to parse the message body and update specific branches
      FetchBranchesJob.perform_later @repository
    end
    render nothing: true
  end
  
  private
  
    def set_repository
      @repository = Repository.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def repository_params
      params.require(:repository).permit(:title, :path, :vcs_type, :weblink_to_commit, :hook_enabled, :hook_login, :hook_password)
    end
    
    def authenticate_hook
      return true if @repository.hook_login.blank? or @repository.hook_password.blank?
      authenticate_or_request_with_http_basic('Hook') do |username, password|
        username == @repository.hook_login && password == @repository.hook_password
      end
    end
    
end

control/app/helpers/repositories_helper.rb
module RepositoriesHelper
  def post_hook_full_url repository
    if repository.hook_login.blank? or repository.hook_password.blank?
      post_hook_repository_url repository
    else
      url_for :controller => :repositories, :action => :post_hook, :user => repository.hook_login, :password => repository.hook_password, :only_path => false
    end
  end
end

control/app/views/repositories/_form.html.haml
= bootstrap_form_for(@repository, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f|
  = f.text_field :title
  = f.text_field :path
  = f.select :vcs_type, @repository.class.vcs_types.collect { |s| [s[0].humanize, s[0]] }, {}, :id => "select-vsc_type"
  = f.text_field :weblink_to_commit, placeholder: "Example: https://bitbucket.org/antlabs_dev/fbbs2/commits/:commit"
  = select2js_for_id "select-vsc_type"
  = f.form_group title: "Whenver remote repository is updated update local branches list" do
    = f.check_box :hook_enabled, label: "Enable POST hook to '#{post_hook_repository_url}'"
    #hook_additionals
      = f.text_field :hook_login
      = f.text_field :hook_password
  = f.primary 'Save'
  - if not defined?(delete_disabled) or not delete_disabled
    = link_to 'Delete this repository', @repository, :method => :delete, :class => "btn btn-danger pull-right", :data => { :confirm => 'Are you sure?' }

control/app/views/repositories/edit.html.haml
- title "Editing repository #{@repository.title}"

%h1.page-header= yield(:title)

.row
  .col-md-12
    = render partial: 'form'

control/app/views/repositories/index.html.haml
- title "List repositories"
  
%h1.page-header= yield(:title)

.row
  .col-md-12
    %table.table.table-striped.table-bordered.table-hover.table-responsive
      %tr
        %th Title
        %th Path
        %th VCS type
        %th More info
        
      - @repositories.each do |repository|
        %tr
          %td= repository.title
          %td= repository.path
          %td= repository.vcs_type.humanize
          %td= link_to content_tag(:span, "", :class => "glyphicon glyphicon glyphicon-list"), repository, :class => "btn btn-default"
          
    = link_to 'Add new repository', new_repository_path, class: "btn btn-primary"

control/app/views/repositories/new.html.haml
- title "Add new repository"

%h1.page-header= yield(:title)

.row
  .col-md-12
    = render partial: 'form', locals: {delete_disabled: true}

control/app/views/repositories/show.html.haml
- title "Repository info"

%h1.page-header= yield(:title)

.row
  .col-md-12
    %dl.dl-horizontal
      %dt Title
      %dd= @repository.title
      %dt Path
      %dd= @repository.path
      %dt VCS type
      %dd= @repository.vcs_type.humanize
      %dt Remote URL
      %dd= "(#{@repository.remote_name}) #{@repository.remote_url}"
      %dt Weblink to commit
      %dd= @repository.weblink_to_commit
      %dt Hook
      %dd= @repository.hook_enabled ? "yes (#{post_hook_full_url @repository})" : "no"
      %dt Created at
      %dd= localtime @repository.created_at
      %dt Updated at
      %dd= localtime @repository.updated_at
    
.row
  .col-md-12
    = link_to 'Edit repository', edit_repository_path(@repository), class: "btn btn-primary"
    = link_to 'Force update remote branches', fetch_branches_repository_path(@repository), class: "btn btn-success", method: :post

.row
  .col-md-12
    %h3 Remote branches
    %ul
      - @repository.branches.each do |b|
        %li= b.name