control/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope "/admin" do
    resources :users, except: [:new, :create] do
      patch :approve, :on => :member
      patch :update_profile, :on => :member
    end
    resources :workers do
      post :request_config, :on => :member
    end
    resources :repositories do
      post :fetch_branches, :on => :member
      post :post_hook, :on => :member
    end
    resources :enviroments
    resources :base_versions
    resources :issue_trackers
    resources :home_page_contents, except: [:show]
    resources :tests_executors
  end
  get 'users/profile', as: 'user_root'
  
  resources :admin, only: [:index]
  resources :build_numbers, only: [:index, :show] do
    post :generate, :on => :collection
  end
  
  resources :enviroments, param: :title, path: "/", only: [] do
    resources :build_jobs, only: [:index, :show, :new, :create, :destroy] do
      delete :stop, :on => :member
      get :check_existing, :on => :collection
      resources :tests_results, only: [:index, :show]
    end
    resources :build_logs, only: [:show]
    resources :build_artefacts, only: [:show], :param => :filename, :filename => /.*/, :format => false
    resources :live_updates, only: [] do
      get :build_jobs, :on => :collection
    end
  end
  resources :dynamic_stylesheets, only: [:index]
  
  get '/:enviroment_title', to: 'build_jobs#enviroments', as: 'home_enviroments'

  root 'home#index'

end

control/app/models/enviroment.rb
class Enviroment < ActiveRecord::Base
  has_many :build_numbers
  belongs_to :repository
  has_and_belongs_to_many :base_versions
  has_many :build_jobs
  belongs_to :issue_tracker
  belongs_to :tests_executor
  
  validates :title, length: {in: 1..100}, uniqueness: true
  validates :default_build_number, numericality: { only_integer: true }, presence: true
  validates :repository, :presence => true
  validates :delete_build_jobs_older_than, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  
  serialize :target_platforms_order
  
  def self.rotate_build_jobs
    Rails.logger.info "Rotating build jobs"
    Enviroment.all.each do |e|
      unless e.delete_build_jobs_older_than.to_i == 0
        build_jobs_to_delete = BuildJob.where("enviroment_id = ? and finished_at <= ?", e.id, Time.now - e.delete_build_jobs_older_than.days)
        ids = build_jobs_to_delete.map{|b| b.id}
        if ids.count > 0
          Rails.logger.warn "Number of BuildJobs to be deleted (older than #{e.delete_build_jobs_older_than.days.to_s}): #{ids.count}, their ids: #{ids.join(', ')}"
          RotateBuildJobsJob.perform_later ids
        else
          Rails.logger.info "Nothing to rotate in enviroment '#{e.title}'"
        end
      end
    end
  end
  
end

control/app/controllers/enviroments_controller.rb
class EnviromentsController < BaseAdminController
  before_filter :set_enviroment, only: [:show, :edit, :update, :destroy]
  before_filter :set_repositories, only: [:new, :edit, :create]
  before_filter :set_base_versions, only: [:new, :edit, :create]
  before_filter :set_issue_trackers, only: [:new, :edit, :create]
  before_filter :set_tests_executors, only: [:new, :edit, :create]
  before_filter :set_target_platforms, only: [:new, :edit, :create]

  # GET /enviroments
  # GET /enviroments.json
  def index
    @enviroments = Enviroment.all
  end

  # GET /enviroments/1
  # GET /enviroments/1.json
  def show
  end

  # GET /enviroments/new
  def new
    @enviroment = Enviroment.new
  end

  # GET /enviroments/1/edit
  def edit
  end

  # POST /enviroments
  # POST /enviroments.json
  def create
    @enviroment = Enviroment.new(enviroment_params)

    respond_to do |format|
      if @enviroment.save
        format.html { redirect_to @enviroment, notice: 'Enviroment was successfully created.' }
        format.json { render :show, status: :created, location: @enviroment }
      else
        format.html { render :new }
        format.json { render json: @enviroment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enviroments/1
  # PATCH/PUT /enviroments/1.json
  def update
    respond_to do |format|
      if @enviroment.update(enviroment_params)
        format.html { redirect_to @enviroment, notice: 'Enviroment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enviroment }
      else
        format.html { render :edit }
        format.json { render json: @enviroment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enviroments/1
  # DELETE /enviroments/1.json
  def destroy
    @enviroment.destroy
    respond_to do |format|
      format.html { redirect_to enviroments_url, notice: 'Enviroment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enviroment
      @enviroment = Enviroment.find(params[:id])
    end

    def set_repositories
      @repositories = Repository.all
    end

    def set_base_versions
      @base_versions = BaseVersion.order(:name => :asc).all
    end

    def set_issue_trackers
      @issue_trackers = IssueTracker.all
    end

    def set_target_platforms
      @target_platforms = TargetPlatform.all_ordered_by_mask @enviroment.target_platforms_order
    end

    def set_tests_executors
      @tests_executors = TestsExecutor.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enviroment_params
      p = params.require(:enviroment).permit(:title, :default_build_number, :repository_id, :branches_filter, :issue_tracker_id,
                                             :target_platforms_order, :tests_executor_id, :tests_enabled_by_default,
                                             :delete_build_jobs_older_than, :base_version_ids => [])
      p[:target_platforms_order] = JSON.parse p[:target_platforms_order]
      p
    end

end

control/app/helpers/enviroments_helper.rb
module EnviromentsHelper
end

control/app/views/enviroments/_form.html.haml
= bootstrap_form_for(@enviroment, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10", :html => {:id => "enviroments_form"}) do |f|
  = f.text_field :title
  = f.number_field :default_build_number
  = f.select :repository_id, @repositories.map{ |p| ["#{p.title} (#{p.vcs_type.humanize} #{p.path})", p.id] }, {}, :id => "select-repository"
  = select2js_for_id "select-repository"
  = f.text_field :branches_filter, :placeholder => "enter a regexp, empty to disable filtering"
  = f.select :issue_tracker_id, @issue_trackers.map{ |p| ["#{p.title}", p.id] }, {include_blank: 'None'}, :id => "select-issue_tracker"
  = select2js_for_id "select-issue_tracker"
  = f.select :tests_executor_id, @tests_executors.map{ |p| ["#{p.title}", p.id] }, {include_blank: 'None'}, :id => "select-tests_executor"
  = select2js_for_id "select-tests_executor"
  = f.number_field :delete_build_jobs_older_than, min: 0, title: "Delete build jobs older than [days]. 0 to keep them forever"
  = f.collection_check_boxes :base_version_ids, @base_versions, :id, :name, label: "Base versions"
  - if @target_platforms.any?
    %label.control-label.col-sm-2= "Target platforms UI order"
    .col-sm-10
      = f.hidden_field :target_platforms_order
      %ul{:id => "sortable_target_platorms", :class => "ui-sortable btn-group-vertical list-unstyled"}
        - @target_platforms.each_with_index do |p, i|
          %li{:class => "ui-state-default btn", :id => "item_#{i}"}= p.title
  .row
    .col-md-11
      .row.form-group
        .control-label.col-sm-2
          = f.label :enable_tests_by_default
        .col-sm-10
          = f.check_box :tests_enabled_by_default, label: "when starting build job checkbox will be checked by default"
    
  = f.primary 'Save'
  - if not defined?(delete_disabled) or not delete_disabled
    = link_to 'Delete this enviroment', @enviroment, :method => :delete, :class => "btn btn-danger pull-right", :data => { :confirm => 'Are you sure?' }

control/app/views/enviroments/edit.html.haml
- title "Editing enviroment #{@enviroment.title}"

%h1.page-header= yield(:title)

.row
  .col-md-12
    = render partial: 'form'

control/app/views/enviroments/index.html.haml
- title "List enviroments"
  
%h1.page-header= yield(:title)

.row
  .col-md-12
    %table.table.table-striped.table-bordered.table-hover.table-responsive
      %tr
        %th Title
        %th Default build number
        %th More info
        
      - @enviroments.each do |env|
        %tr
          %td= env.title
          %td= env.default_build_number
          %td= link_to content_tag(:span, "", :class => "glyphicon glyphicon glyphicon-list"), env, :class => "btn btn-default"
          
    = link_to 'Add new enviroment', new_enviroment_path, class: "btn btn-primary"

control/app/views/enviroments/new.html.haml
- title "Add new enviroment"

%h1.page-header= yield(:title)

.row
  .col-md-12
    = render partial: 'form', locals: {delete_disabled: true}

control/app/views/enviroments/show.html.haml
- title "Enviroment info"

%h1.page-header= yield(:title)

.row
  .col-md-12
    %dl.dl-horizontal
      %dt Title
      %dd= @enviroment.title
      %dt Default build number
      %dd= @enviroment.default_build_number
      %dt Repository
      - unless @enviroment.repository.nil?
        %dd= link_to @enviroment.repository.title, @enviroment.repository
      - else
        %dd none
      - unless @enviroment.issue_tracker.nil?
        %dt Issue tracker
        %dd= link_to @enviroment.issue_tracker.title, @enviroment.issue_tracker
      - unless @enviroment.tests_executor.nil?
        %dt Tests executor
        %dd= link_to @enviroment.tests_executor.title, @enviroment.tests_executor
      %dt Branches filter regex
      %dd= @enviroment.branches_filter
      %dt Base versions
      %dd= @enviroment.base_versions.map{|b| b.name}.join(", ")
      - unless @enviroment.target_platforms_order.nil?
        %dt Target platfroms UI order
        %dd= @enviroment.target_platforms_order.join(", ")
      %dt Delete build jobs older than [days]
      %dd= @enviroment.delete_build_jobs_older_than
      %dt Created at
      %dd= localtime @enviroment.created_at
      %dt Updated at
      %dd= localtime @enviroment.updated_at
    
.row
  .col-md-12
    = link_to 'Edit enviroment', edit_enviroment_path(@enviroment), class: "btn btn-primary"